In [5]:
#Exercise 1:
import numpy as np
a = np.array([1, 2])
b = np.array([2, 1])
c = np.array([-2, -1])
dot_ab = np.dot(a,b)
dot_bc = np.dot(b,c)
print(dot_ab)
print(dot_bc)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
cos_ab = dot_ab/(norm_a*norm_b)
print(cos_ab)
radian_ab = np.arccos(cos_ab)
degree_ab = np.degrees(radian_ab)
print(f"cos_ab = {cos_ab}")
print(f"radian_ab = {radian_ab}")
print(f"degree_ab = {degree_ab}")

4
-5
0.7999999999999998
cos_ab = 0.7999999999999998
radian_ab = 0.6435011087932847
degree_ab = 36.86989764584404

In [6]:
# Matrix and Inverse Matrix
# 2*x - y = 0
#   x + y = 3
# ==> x = 1, y = 2
A = np.array([[2,-1], [1,1]])
B = np.array([[0], [3]])
# Ax = b ==> A^-1*A*x = A^-1*b ==> I*x = A^-1*b ==> x = A^-1 * b
inv_A = np.linalg.inv(A)
print(inv_A)
I = np.round(np.dot(inv_A, A), 3)
print(I)

X = np.dot(inv_A, B)
print("Nghiem cua he phuong trinh la :")
print(X)

[[ 0.33333333  0.33333333]
 [-0.33333333  0.66666667]]
[[ 1. -0.]
 [ 0.  1.]]
Nghiem cua he phuong trinh la :
[[1.]
 [2.]]

In [11]:
import pandas as pd
AppleStock = [70 , 72 , 80 , 75 , 69 , 85 ]
MSStock    = [120, 125, 130, 128, 110, 150]
GOStock    = [200, 150, 120, 170, 250, 280]

df = pd.DataFrame({"AppleStock" : AppleStock, "MSStock" : MSStock, "GOStock" : GOStock})
display(df)
CovarianceDF = df.cov()
CorrelationDF = df.corr()

display(CovarianceDF)
display(CorrelationDF)

   AppleStock  MSStock  GOStock
0          70      120      200
1          72      125      150
2          80      130      120
3          75      128      170
4          69      110      250
5          85      150      280

            AppleStock     MSStock  GOStock
AppleStock   38.966667   77.566667     51.0
MSStock      77.566667  176.166667    165.0
GOStock      51.000000  165.000000   3710.0

            AppleStock   MSStock   GOStock
AppleStock    1.000000  0.936196  0.134133
MSStock       0.936196  1.000000  0.204096
GOStock       0.134133  0.204096  1.000000